############################
## CHANGE THESE
############################

baseURL: "https://biglonglong.github.io"
title: 龙犊&小窝🪹~

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
