############################
## CHANGE THESE
############################

baseURL: "https://biglonglong.github.io"
title: 龙犊&小窝🪹~
copyright: ":smile:"

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true


markup:
  _merge: deep
