############################
## CHANGE THESE
############################

baseURL: "https://biglonglong.github.io/biglonglong.github.io"
title: biglonglong.github.io

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
