############################
## Author
############################

author:
  name: biglonglong
  image: avatar.jpg
  greeting: "USTCer🎓 | noter📝 | coder💻 | beginner💪"
  icon: ":anger:"

############################
## Links
############################

links:
  - email: mailto:1522262926@qq.com
  - github: https://github.com/biglonglong
  - link: https://www.xiaohongshu.com/user/profile/5f39f522000000000100a829
  - spotify: /index.xml
  - soundcloud: https://pan.baidu.com/s/1VWiI7siC3b6wNRITmbqGpg?pwd=627k
  # - certifications: /resume.pdf

###############################
## OpenGraph & Twitter Cards
###############################

title: 龙犊&小窝🪹~
description: "Personal Site about Note, Journal, and Code, builded with Qubt & Hugo"
images:
  - thumbnail.png
