############################
## Author
############################

author:
  name: biglonglong
  image: avatar.jpg
  greeting: 👊和世界构造羁绊吧，不要害怕，Passion!👊
  icon: ":anger:"

############################
## Links
############################

links:
  - email: mailto:1522262926@qq.com
  - github: https://github.com/biglonglong
  - link: https://www.xiaohongshu.com/user/profile/5f39f522000000000100a829
  - spotify: /index.xml
  - soundcloud: https://pan.baidu.com/s/1VWiI7siC3b6wNRITmbqGpg?pwd=627k
  # - certifications: /resume.pdf

###############################
## OpenGraph & Twitter Cards
###############################

title: 龙犊&小窝🪹~
description: "Personal Site about Note, Journal, and Code, builded with Qubt & Hugo"
images:
  - thumbnail.png

###############################
## Latex math
###############################

# To configure Latex rendering on all pages, change to: true
#
# To only add Latex rendering on pages that need it, set in the frontmatter
# of each page that needs it:
#   params:
#     math: true
# This option will allow better performance, as it'll only load
# the extra JS when needed.
math: false

buildDate: "2024-11-25T07:52:34Z"

busuanzi:
    enable: true

readSpeed: 2