############################
## Author
############################

author:
  name: biglonglong
  image: avatar.jpg
  greeting: "[USTCer🎓](https://www.ustc.edu.cn/) -> noting📝 | journaling🌤 | coding💻"
  icon: ":anger:"

############################
## Links
############################

links:
  - email: mailto:1522262926@qq.com
  - github: https://github.com/biglonglong
  - rss: /index.xml
  - resume: /resume.pdf
  # - website: 
  # - link:
  

###############################
## OpenGraph & Twitter Cards
###############################

title: 龙犊&小窝🪹~
description: "Personal Site about Note, Journal, and Code, builded with Qubt & Hugo"
images:
  - thumbnail.png
