# ================================================================================
# GitHub Actions Workflow: Clean & Build & Deploy Hugo Site to GitHub Pages
# ================================================================================
# Setup Instructions: Go to Settings -> Pages -> Build and deployment -> Set Source to "GitHub Actions"

name: Build & Clean & Deploy Hugo site to Pages

# Trigger on push to main branch (excluding specific files)
on:
  push:
    branches:
      - main
    paths-ignore:
      - "draft/**"
      - "LICENSE"
      - "README.md"

# Change the above to this to deploy only on releases
# on:
#   release:
#     types: [published]

  # Allow running workflow from Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write
  pages: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: 'pages'
  cancel-in-progress: true

# Default shell for all run commands
defaults:
  run:
    shell: bash


jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: 🗑 Delete deployment
        uses: strumwolf/delete-deployment-environment@v2
        # https://github.com/marketplace/actions/delete-deployment-environment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true
  
  build:
    runs-on: ubuntu-latest
    needs: cleanup
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      # Remember to keep the version up to date with your local build environment
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          # renovate: datasource=github-tags depName=golang/go
          go-version: '1.23.3'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          # renovate: datasource=github-releases depName=gohugoio/hugo
          hugo-version: '0.136.5'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
